# Generated by Django 4.2.6 on 2023-10-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeChecklistPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalYear', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='DegreeChecklist/pdfs/')),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
    ]
