# Generated by Django 4.2.6 on 2023-11-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('DegreeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DegreeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=200)),
                ('CollegeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.college')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeChecklistPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalYear', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='DegreeChecklist/pdfs/')),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='DepartmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.department'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=50)),
                ('CourseName', models.CharField(max_length=200)),
                ('Hrs', models.IntegerField()),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalYear', models.CharField(max_length=20)),
                ('RowID', models.IntegerField()),
                ('RequirementGroup', models.CharField(max_length=200)),
                ('RequirementSubGroup', models.CharField(max_length=200)),
                ('CourseInstruction', models.CharField(max_length=500)),
                ('Hrs', models.IntegerField()),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
            options={
                'unique_together': {('DegreeID', 'FiscalYear', 'RowID')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalYear', models.CharField(max_length=20)),
                ('RowID', models.IntegerField()),
                ('YearNumber', models.IntegerField()),
                ('Semester', models.CharField(max_length=20)),
                ('CourseInstruction', models.CharField(max_length=500)),
                ('Hrs', models.IntegerField()),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
            options={
                'unique_together': {('DegreeID', 'FiscalYear', 'RowID')},
            },
        ),
    ]
